### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by casoetan** [yunabe/lgo#23]
Hi.

Any plans to support other OSes and timeframe?

**Comment by yunabe** [comment]
lgo kernel relies on [-buildmode=shared and -linkshared](https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies) of go build.
As of go1.10, -linkshared is still experimental feature and supported only in Linux, thus there is no short term plan to support other OSes.

go started to support buildmode=shared on Mac from go1.10. I hope -linkshared is also supported on Mac in upcoming versions of Go. But I don't know they have plans.

**Comment by casoetan** [comment]
Thanks for the update, hopefully linkshared comes to to macs soon.
