### ISSUE TITLE
Need documenting difference jupyter notebook bin names.

### ISSUE THREAD

**Issue by baram204** [yunabe/lgo#26]
I tried install nbextensions got erros.

and figured out bin file name is different from nomals.

[jupyter-contrib](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) tells `jupyter nbextensions_configurator enable --user`, but there is no contrib things.

so many tries. so get `the bin` path like below.

```
$ pip uninstall jupyter_nbextensions_configurator
Uninstalling jupyter-nbextensions-configurator-0.4.0:
  /home/gopher/.local/bin/jupyter-nbextensions_configurator
  /home/gopher/.local/lib/python2.7/site-packages/jupyter_nbextensions_configurator-0.4.0.dist-info/DESCRIPTION.rst

```

lgo has another bin names.

```
~/.local/bin$ ls
easy_install                 jupyter-kernelspec
easy_install-2.7             jupyter-migrate
iptest                       jupyter-nbconvert
iptest2                      jupyter-nbextension
ipython                      jupyter-nbextensions_configurator
ipython2                     jupyter-notebook
jsonschema                   jupyter-run
jupyter                      jupyter-serverextension
jupyter-bundlerextension     jupyter-troubleshoot
```

I don't know what's origin, but we need documentation about it.

for avoiding so many time wasting.

**Comment by yunabe** [comment]
Thank you for the feedback. But I'm not quite sure what was the problem.

> I tried install nbextensions got erros.
Please provide the process to reproduce this issue and what errors you actually saw.

**Comment by baram204** [comment]
A-ha! I didn't know what jupyter subcommand and jupyter scripts are.

I think there some path settings for `~/.local/bin`.

1. Jupyter subcommand not working. But, there are already jupyter scripts.

```
$ jupyter contrib nbextension install --user
Error executing Jupyter command 'contrib': [Errno 2] No such file or directory
```

From [jupyter contrib nbextensions repo](https://github.com/ipython-contrib/jupyter_contrib_nbextensions#2-install-javascript-and-css-files) said.

```
$ ls ~/.local/bin *contrib
jupyter-contrib
```

2. Jupyter script require some kind of directory paths. include subcommand

```
$ jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```

3. notebook subcommand working. and It's script also exist already.

```
$ jupyter-notebook
[I 23:02:57.660 NotebookApp] The port 8888 is already in use, trying another port.
```

```
$ find / -name *notebook*
/home/gopher/.local/bin/jupyter-notebook
find: ��/etc/ssl/private��: Permission denied
find: ��/var/cache/apt/archives/partial��: Permission denied
find: ��/var/cache/ldconfig��: Permission denied
find: ��/root��: Permission denied
/usr/local/bin/jupyter-notebook

```

4. difference between two subcommands(notebook and contrib) is path.

**Comment by baram204** [comment]
OK. It's not problem.
