### ISSUE TITLE
Python3 Error: ImportError: No module named 'commands'

### ISSUE THREAD

**Issue by ekaakurniawan** [yunabe/lgo#42]
Need to use `subprocess` for Python3.

https://github.com/yunabe/lgo/blob/dbcd29454c1158750dbd24d359c4635635c06f88/bin/install_kernel#L9

Replace:
`import command`
with:
`import subprocess`

https://github.com/yunabe/lgo/blob/dbcd29454c1158750dbd24d359c4635635c06f88/bin/install_kernel#L59

and:
`        rc, gopath = commands.getstatusoutput('go env GOPATH')`
with:
`        rc, gopath = subprocess.getstatusoutput('go env GOPATH')`

**Comment by yunabe** [comment]
Thank you for the feedback!
