### ISSUE TITLE
Show longer documentation

### ISSUE THREAD

**Issue by koneko096** [yunabe/lgo#53]
Any way to show longer Docstring like Python kernel's?

For example to show docs for GoStringer 
![image](https://user-images.githubusercontent.com/9217338/39091280-233bc036-461b-11e8-9aed-8fba44e4f9f1.png)
looks like doc is truncated

Usually in Python I'll use 
`?fmt.GoStringer()`
but apparently it doesn't work as well

**Comment by yunabe** [comment]
Press `Shift-Tab` twice or four times to expand the docstring.
