### ISSUE TITLE
Error using lgo with juypterhub

### ISSUE THREAD

**Issue by wburningham** [yunabe/lgo#56]
I'm trying to install lgo so I can use it in notebooks on jupyterhub. I'm using the base jupyterhub image and added the commands to install lgo.

The [Dockerfile I am using is here](https://gist.github.com/wburningham/d0cb07cf26f558db4468e8108bdea414). After starting the container I 

1. add a user (using the `adduser` cmd from within `docker exec`)
1. login
1. create a notebook using the lgo kernal
1. get an error

The error I am seeing is 
```
[I 2018-04-23 03:09:17.306 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (1/5), new random ports
2018/04/23 03:09:17 LGOPATH is empty
[I 2018-04-23 03:09:20.320 SingleUserNotebookApp restarter:110] KernelRestarter: restarting kernel (2/5), new random ports
2018/04/23 03:09:20 LGOPATH is empty
```

If I `echo $LGOPATH` inside the running container, I see `/lgo` so not sure why that error is happening.

Any help with a working Dockerfile for running jupyterhub with lgo installed?

**Comment by yunabe** [comment]
Sorry for the slow response. I'm not familiar with JupyterHub.
But this error message means your jupyter process is not executed LGOPATH env var properly.
According to google search, we may need to use `c.Spawner.environment` or `c.Spawner.keep_env` to set env variables in JupyterHub properly?
http://jupyterhub.readthedocs.io/en/latest/api/spawner.html

**Comment by david11rsww** [comment]
I have the same problem, and  @yunabe 's method solved it. But, when I run `sudo jupyterhub`, the sudo addition makes a new problem. When I run the kernel, something is wrong.
```shell 
Failed to build a shared library of github.com/yunabe/lgo/sess7b2274696d65223a313533343134333033303837323039343539377d/exec1: exec: "go": executable file not found in $PATH
```
Need some helps too...

**Comment by yunabe** [comment]
I'm closing this bug since there is no update for a while.
