### ISSUE TITLE
Go (lgo) Kernel not available when container is created with volume bind

### ISSUE THREAD

**Issue by dirkolbrich** [yunabe/lgo#62]
The docker image seems to have a problem with bind volumes and finding the Go (lgo) Kernel in the Jupyter notebook.

If I start the standard way:
```bash
docker pull yunabe/lgo
docker run --name lgo -p 8888:8888 -d yunabe/lgo
docker exec lgo jupyter notebook list 
```
Everything is fine. Open the browser at localhost:8888 and enter the Jupyter notebook. If I start a new notebook, I can choose between Go(lgo) and Python 2 Kernel.

But if I create the container and bind a volume to it, the Go(lgo) Kernel is not available within the Jupyter notebook:
```bash
docker pull yunabe/lgo
docker run --name lgo -v ~/jupyter:/home/gopher -p 8888:8888 -d yunabe/lgo
docker exec lgo jupyter notebook list 
```

I am now able to create new notebooks, which get synchronized to the local folder, but not with Go. What am I missing?

Docker version is the following:
```bash
$docker docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:13:02 2018
 OS/Arch:      darwin/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:22:38 2018
  OS/Arch:      linux/amd64
  Experimental: true
```

**Comment by yunabe** [comment]
In the docker image (`yunabe/lgo`), the jupyter kernel configuration is installed in the home directory (`/home/gopher`).

```
>> docker run --rm yunabe/lgo sh -c 'ls -la ~/.local/share/jupyter/kernels'
total 12
drwxr-xr-x 3 gopher gopher 4096 May 10 14:34 .
drwxr-xr-x 3 gopher gopher 4096 May 10 14:34 ..
drwxr-xr-x 2 gopher gopher 4096 May 10 14:34 lgo
```

Because you overwrite `/home/gopher` by binding `~/jupyter` to it, jupyter notebook can not find kernel configurations installed in `/home/gopher`.

To fix the issue, you should mount `~/jupyter` to a subdirectory of `/home/gopher` like `/home/gopher/jupyter`.

**Comment by dirkolbrich** [comment]
Wouldn't it be better them to move the jupyter kernel configuration one above the home directory (/home), so (/home/goper) can be connected safely to a local folder:

I tweaked the Dockerfile to this, set $HOME to (/home) and WORKDIR to (/home/gopher):

```dockerfile
# Add a non-root user with uid:1000 to follow the convention of mybinder to use this image from mybinder.org.
# https://mybinder.readthedocs.io/en/latest/dockerfile.html
ARG NB_USER=gopher
ARG NB_UID=1000
ENV HOME /home
RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    --home ${HOME} \
    ${NB_USER}
RUN chown -R ${NB_USER}:${NB_USER} ${HOME} $GOPATH $LGOPATH
USER ${NB_USER}
WORKDIR ${HOME}/${NB_USER}
```

**Comment by yunabe** [comment]
> Wouldn't it be better them to move the jupyter kernel configuration one above the home directory (/home), so (/home/goper) can be connected safely to a local folder. 

Why do you want to use `/home` instead of `/home/gopher` as a home directory?

> This way no other user would run into this problem.

Even if it's renamed to `/home` from `/home/gopher`, we can still break jupyter configuration if we mount a volume to the new home directory. I'm not sure why we can mitigate the risk of running into the same issue by renaming it.

**Comment by dirkolbrich** [comment]
Well, to keep the kernel installation and the user generated files separate. The kernel and anything regarding the jupyter runtime stays in `/home`. All user generated `.ipynb`notebooks stay in `/home/gopher`. I can bind a local folder to the docker `/home/gopher` folder, without overwriting the kernel installation.
This way all notebooks are available on my local drive, I don't loose them, if I delete the docker container. And I can copy a notebook (say, I received it from a fellow colleague via email) to the local folder, it is immediately available in the docker runtime.

It works on my machine. You can close this issue, as it is solved for me.
Thank you for your time and your awesome Go kernel. 👌

**Comment by yunabe** [comment]
> Well, to keep the kernel installation and the user generated files separate.

That makes sense. But I'm still not sure why renaming the home dir would help the isolation. Without renaming, you can still bind your local directory to a subdirectory of `/home/gopher`. You can also set a subdirectory of `/home/gopher` to `WORKDIR`.

Another approach to isolate jupyter configuration and home dir is installing jupyter kernel config as `root`. But I want to keep the jupyter kernel configuration into a normal user directory unless there is a real benefit to move it into `root`.

> Thank you for your time and your awesome Go kernel. 👌
☺
