### ISSUE TITLE
wrong variable value when running in jupyter notebook

### ISSUE THREAD

**Issue by wgong** [yunabe/lgo#73]
Hi,
I am running this example https://gobyexample.com/worker-pools:
On Ubuntu, 
$ go run worker-pools.go
worker 3 started  job 1
worker 1 started  job 2
worker 2 started  job 3
worker 1 finished job 2
worker 1 started  job 4
worker 3 finished job 1
worker 3 started  job 5
worker 2 finished job 3
worker 3 finished job 5
worker 1 finished job 4

But inside Jupyter, calling main() function gives:
worker 4 started  job 1
worker 4 started  job 2
worker 4 started  job 3
worker 4 finished job 3
worker 4 started  job 4
worker 4 finished job 1
worker 4 started  job 5
worker 4 finished job 2
worker 4 finished job 5
worker 4 finished job 4

Notice that worker ids remain as 4, not [1,2,3]

This is reproducible even I restart kernel, or restart a new notebook

**Comment by yunabe** [comment]
Thank you for the report. I added an example to reproduce this bug.
https://nbviewer.jupyter.org/github/yunabe/lgo/blob/master/examples/bugs.ipynb#Bug:-functions-and-arguments-in-go-statement-are-not-bound-immediately
