### ISSUE TITLE
replace glog with log

### ISSUE THREAD

**Issue by yasushi-saito** [yunabe/lgo#74]
I've been trying to use gojupyterscaffold to write a new kernel (not Go), but I found that it uses glog, which defines its own set of flags, e.g., log_dir and logtostderr, which conflicts with other logging modules we are using. Is it possible to stop using glog in lgo's library packages and instead use the standard log? Or at least have some indirection mechanism so that they don't need to hardcode dependencies on glog?

**Comment by yunabe** [comment]
Sorry for the slow response.

Yes, `gojupyterscaffold` is designed for general Jupyter kernels in Go and I'm happy if it's used from other kernels. To use the library from other kernels, I also think we should reduce unnecessary dependencies from `gojupyterscaffold`.

> Or at least have some indirection mechanism so that they don't need to hardcode dependencies on glog?

I got used to `glog` and I want to keep using it in my kernel. Thus, I will remove the direct dependency from  `gojupyterscaffold` to `glog` by introducing indirection mechanism. Sounds good?

**Comment by yasushi-saito** [comment]
Sounds good. Thanks.

**Comment by yunabe** [comment]
I removed the direct dependency to `golang/glog`. Now `gojupyterscaffold` record logs with `log` by default. We  can change the logger by [`SetLogger`](https://godoc.org/github.com/yunabe/lgo/jupyter/gojupyterscaffold#SetLogger).

If you have requests for the library, feel free to file bugs or send PRs.
